### ISSUE TITLE
java版如何启动

### ISSUE THREAD

**Issue by symsimmy** [huaxiaozhou/android-protection#1]
我照着你写的博文一步一步的实践，最后java版的启动项目无法启动，会报错：

> r E/AndroidRuntime: FATAL EXCEPTION: main
                                                                               Process: com.symsimmy.dynamicdexloader, PID: 16107
                                                                               java.lang.RuntimeException: Unable to instantiate activity ComponentInfo{com.symsimmy.dynamicdexloader/com.symsimmy.dexloader.MainActivity}: java.lang.ClassNotFoundException: Didn't find class "com.symsimmy.dexloader.MainActivity" on path: DexPathList[[zip file "/data/app/com.symsimmy.dynamicdexloader-1/base.apk"],nativeLibraryDirectories=[/data/app/com.symsimmy.dynamicdexloader-1/lib/arm64, /system/lib64, /vendor/lib64]]
                                                                                   at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2604)
                                                                                   at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2788)
                                                                                   at android.app.ActivityThread.-wrap12(ActivityThread.java)
                                                                                   at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1503)
                                                                                   at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                                   at android.os.Looper.loop(Looper.java:154)
                                                                                   at android.app.ActivityThread.main(ActivityThread.java:6209)
                                                                                   at java.lang.reflect.Method.invoke(Native Method)
                                                                                   at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:865)
                                                                                   at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:755)
                                                                                Caused by: java.lang.ClassNotFoundException: Didn't find class "com.symsimmy.dexloader.MainActivity" on path: DexPathList[[zip file "/data/app/com.symsimmy.dynamicdexloader-1/base.apk"],nativeLibraryDirectories=[/data/app/com.symsimmy.dynamicdexloader-1/lib/arm64, /system/lib64, /vendor/lib64]]
                                                                                   at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
                                                                                   at java.lang.ClassLoader.loadClass(ClassLoader.java:380)
                                                                                   at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
                                                                                   at android.app.Instrumentation.newActivity(Instrumentation.java:1094)
                                                                                   at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2594)
                                                                                   at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2788) 
                                                                                   at android.app.ActivityThread.-wrap12(ActivityThread.java) 
                                                                                   at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1503) 
                                                                                   at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                                                   at android.os.Looper.loop(Looper.java:154) 
                                                                                   at android.app.ActivityThread.main(ActivityThread.java:6209) 
                                                                                   at java.lang.reflect.Method.invoke(Native Method) 
                                                                                   at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:865) 
                                                                                   at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:755)

**Comment by symsimmy** [comment]
想问问到底是哪里出错了

**Comment by huaxiaozhou** [comment]
你这个错误是Caused by: java.lang.ClassNotFoundException: Didn't find class "com.symsimmy.dexloader.MainActivity" on path:找不到MainActivity。你反编译一下dex看下有没有这个类，我怀疑加固的时候没有把这类打包进去
